Models/ErrorViewModel.cs
namespace Assignment5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Person.cs
namespace Assignment5.Models
{
    public class Person
    {
        public int PersonID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Controllers/HomeController.cs
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assignment5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index2()
        {
            ViewBag.Title = "This is index2.";
            return View();
        }

        [HttpGet]
        public IActionResult ValidateAge()
        {
            ViewBag.Title = "Validate age for voting";
            Person person = new Person();
            return View(person);
        }

        [HttpPost]
        public IActionResult ValidateAge(Person person)
        { 
            if (person.Age >= 18)
            {
                ViewBag.Message = "You are eligible to vote.";
            }
            else
            {
                ViewBag.Message = "Sorry! You are not old enough to vote.";
            }
            return View();
        }

        public IActionResult Activity4()
        {
            return View();
        }

        public IActionResult Activity5()
        {
            return View();
        }

        public IActionResult Activity6()
        {
            return View();
        }
    }
}

ViewComponents/SimpleViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Assignment5.ViewComponents
{
    [ViewComponent(Name = "Simple")]
    public class SimpleViewComponent :ViewComponent
    {
        public IViewComponentResult Invoke(string additionalData)
        {
            var data = GetSampleData(additionalData);
            return View(data);
        }

        private List<string> GetSampleData(string additionalData)
        {
            List<string> data = new List<string>();
            data.Add("One");
            data.Add("Two");
            data.Add("Three");
            data.Add("Four");
            data.Add(additionalData);
            return data;
        }
    }
}

Views/Home/Activity4.cshtml
@{
    ViewBag.Title = "Activity4";
}

<h1>@ViewBag.Title</h1>
<body>
    @Html.Partial("_PartialViewHelloWorld")
</body>

Views/Home/Activity5.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>ACTVITY 5 - VIEW COMPONENTS</h1>
<p>This is a sample web page.<br />
    <div>
        @*@await Component.InvokeAsync("ViewComponents/Simple",new {additionalData = "five"})*@
        @await Component.InvokeAsync("Simple", new { additionalData = "Five" })
    </div>

</p>

Views/Home/Activity6.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Activity 6</h1>
<h3>About Us</h3>
We are one of the biggest electronics retail store serving millions of people across the nation. blah.blah. blah
<br />
If you want to hear great offers from us
<email>atka.ali@students.au.edu.pk</email>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div>
    <a href = @Url.Action("Index2","Home")>Navigate to Activity 2</a>
</div>

<div>
    <a href=@Url.Action("ValidateAge", "Home")>Navigate to Activity 3</a>
</div>

<div>
    <a href=@Url.Action("Activity4", "Home")>Navigate to Activity 4 - Partial View</a>
</div>
<div>
<a href=@Url.Action("Activity5", "Home")>Navigate to Activity 5 - View Components</a>
</div>

<div>
    <a href=@Url.Action("Activity6", "Home")>Navigate to Activity 6 - Tag Helpers</a>
</div>
<div>
<h2> Views Demo 1</h2>
 @{
        int i = 5;
    }
    Value: @i
</div>

<div>
<h2> Views Demo 2</h2>
        <ul>
        @{ for (int j = 0; j<5; j++)
            {
                <li>@(j+1)</li>
            }
        }
    </ul>
</div>

<div>
    <h2> Views Demo 3</h2>
    <ul>
    @{
        int k = 0;
        while (k < 5)
        {
                <li>@(k+1)</li>
                k++;
            }
        }
    </ul>
</div>

<div>
    <h2> Views Demo 4</h2>
    @{
        List<int> ints = new List<int>
        {
            1,2,3,4,5
        };
        foreach(int l in ints)
        {<ul>
                <li> @l</li>
            </ul>
        }
    }
</div>

<div>
    <h2>Views Demo 5</h2>
    @{
        int x = 5;
        if (x < 5)
        {
            <text>x is less than 5. The value of x is: @x</text>
        }
        else
        {
            <text> x is greater than 5. The value of x is @x.</text>
        }
      }
        </div>

Views/Home/Index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>INDEX2.CSHTML</h1>
Hello! This text will be rendered in the body of the layout page.<br />

Views/Home/ValidateAge.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Person
@using (Html.BeginForm("ValidateAge","Home", FormMethod.Post))
{
    <table>
        <tr>
            <td>@Html.LabelFor(Model => Model.Name)</td>
            <td>@Html.TextBoxFor(Model => Model.Name)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(Model => Model.Age)</td>
            <td>@Html.TextBoxFor(Model => Model.Age)</td>
        </tr>
        <tr>
            <td colspan = "2"><input type="submit" value = "Submit"/></td>  
        </tr>
    </table>
}

@if (ViewBag.Message != null)
{
    <b>@ViewBag.Message</b>
}

Views/Shared/Components/Simple/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<string>
<h3>Sample list</h3>
<ul>
    @foreach(var item in Model)
    {
        <li>@item</li>
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment-5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment-5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment-5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _213002_Assignment05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PartialViewHelloWorld.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<b>This table and below content is coming from the partial view</b>
<table border="1">
    <tr>
        <th>Employee Number</th>
        <th>Employee Name</th>
    </tr>

    <tr>
        <td>10012</td>
        <td>Kate Middleton</td>
    </tr>

    <tr>
        <td>10013</td>
        <td>Jennifer Lopez</td>
    </tr>
</table>